# Generated by Django 2.2 on 2021-08-16 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Favorite_Books_App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
